### ISSUE TITLE
ApiError: failed to check vault seal state

### ISSUE THREAD

**Issue by yogibear15** [f5devcentral/ps-convert#20] opened 2023-08-23 21:37 UTC
Hello,

We are experiencing failure of Policy Supervisor where any policy related actions (import, convert or deploy) hit an error seemingly related to a 503 error returned from vault.policysupervisor.io.

Error details:
```
{
    "name": "ApiError",
    "url": "https://policysupervisor.io/api/v1/commands/import-from-file",
    "status": 500,
    "statusText": "Internal Server Error",
    "body": {
        "code": 2,
        "message": "failed to trigger pipeline: failed to check vault seal state: Error making API request.\n\nURL: GET https://vault.policysupervisor.io/v1/sys/seal-status\nCode: 503. Raw Message:\n\n",
		
		
		
		Error 500 - Internal Server Error
failed to check vault seal state: Error making API request.

URL: GET https://vault.policysupervisor ...

{
    "name": "ApiError",
    "url": "https://policysupervisor.io/api/v1/commands/find-endpoints",
    "status": 500,
    "statusText": "Internal Server Error",
    "body": {
        "code": 2,
        "message": "failed to check vault seal state: Error making API request.\n\nURL: GET https://vault.policysupervisor.io/v1/sys/seal-status\nCode: 503. Raw Message:\n\n",
        "details": []
    },
    "request": {
        "method": "POST",
        "url": "/api/v1/commands/find-endpoints",
        "body": {
            "providerId": "d4c9860b-a4dd-4c6d-b239-b6810c6102c8"
        },
        "errors": {
            "400": "Invalid argument",
            "401": "Returned when the user does not have permission to access the resource.",
            "404": "Resource was not found.",
            "500": "Internal server error"
        }
    }
}

```

Policy Supervisor is not usable due to this, so a prompt response would be apprecaited.  Thanks

**Comment by nikg** [comment] 2023-11-13 18:48
Should be fixed, instability was caused by Vault config.

**Closed by nikg** 2023-11-13 18:48 UTC
